### ISSUE TITLE
Context and Direction Research Presentations 4/9

### ISSUE THREAD

**Issue by mferrato** [mferrato/CISC489-Project-Machine-Learning#1]
Prepare a 5-10 minute presentation about a research paper you found relevant to your project direction. Your presentation should include:

1. Context. What problem is the research paper solving or exploring?

2. Results. What results did they find in their research?

3. Future direction. What future directions did they see possible with the algorithm, model, software, etc. that they produced?

4. Why is this paper relevant to your project and your direction?

**Comment by mferrato** [comment]
Created google slides link to work on the presentation: 

https://docs.google.com/presentation/d/1L15eL-12P8TdiLMW7sRCQ1U48jI8ZYod1nweK3KG3NQ/edit?usp=sharing

**Comment by efwright** [comment]
Finished the slides
